[versions]
java-target = "21"
java-toolchain = "21"
ktlint = "1.4.0"

agp = "8.13.1"
app-gradle-plugins = "0.4.1"
baselineprofile = "1.4.1"
dependency-analysis = "3.5.1"
gradle-doctor = "0.12.1"
kotlin = "2.2.21"
kotlinPoet = "2.2.0"
ksp="2.3.2"
moko-resources = "0.25.2"
publish = "0.35.0"
skie = "0.10.8"
spotless = "8.1.0"

[libraries]
baselineprofile-gradlePlugin = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "baselineprofile" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resources" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }

# Build logic dependencies
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
dependency-analysis-gradle-plugin = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependency-analysis" }
gradle-doctor-gradle-plugin = { group = "com.osacky.doctor", name = "doctor-plugin", version.ref = "gradle-doctor" }
skie-gradle-plugin = { module = "co.touchlab.skie:gradle-plugin", version.ref = "skie" }
ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin",  version.ref = "ksp" }

[plugins]
app-root = { id = "io.github.thomaskioko.gradle.plugins.root",  version.ref = "app-gradle-plugins" }
app-spotless = { id = "io.github.thomaskioko.gradle.plugins.spotless",  version.ref = "app-gradle-plugins" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

